theme: jekyll-theme-minimal
title: Amir REKIK homepage
description: Welcome to my website presentation. Here you will find everything you need to know me. 
However, nothing is better than coming to meet me by email or by telephone.
